/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

use std::path::Path;
use std::path::PathBuf;

use anyhow::Result;
use pyrefly_python::module_name::ModuleName;
use ruff_python_ast::Mod;
use ruff_python_ast::ModModule;
use ruff_python_ast::PySourceType;
use ruff_python_parser::ParseOptions;

use crate::pyrefly::sys_info::PythonVersion;
use crate::runner::default_python_version;
use crate::runner::to_ruff_version;

// Operations on a single module, either .py or .pyi

/// Result of parsing a Python module in string form into an AST.
pub struct ParsedModule {
    pub name: ModuleName,
    pub ast: ModModule,
    pub source_type: PySourceType,
    /// Whether this module came from an `__init__.py` file.
    /// Affects relative import resolution: in `__init__.py`, `.foo` resolves
    /// relative to the current package rather than the parent package.
    pub is_init: bool,
    /// Whether the source file is generated Thrift codegen: thrift-py-deprecated
    /// `.ttypes` or thrift-python `.thrift_types`.
    /// These modules are treated as safe (all effects removed) during analysis.
    pub is_thrift_generated: bool,
    /// The first syntax error ruff reported while (error-recoveringly) parsing,
    /// if any. The AST is still populated best-effort; the real-file read boundary
    /// surfaces this (treating a broken file as missing), while test snippets and
    /// embedded stubs deliberately ignore it.
    first_syntax_error: Option<String>,
    /// Sorted array of all of the byte positions of line numbers.
    newline_positions: Vec<u32>,
}

impl ParsedModule {
    pub fn is_stub(&self) -> bool {
        self.source_type == PySourceType::Stub
    }

    /// The first syntax error ruff reported while parsing, or `None` if the
    /// source parsed cleanly. The AST is populated best-effort regardless.
    pub fn first_syntax_error(&self) -> Option<&str> {
        self.first_syntax_error.as_deref()
    }

    pub fn byte_to_line_number(&self, pos: u32) -> usize {
        let idx = match self.newline_positions.binary_search(&pos) {
            Ok(n) => n,
            Err(n) => n,
        };

        // Check if we're out-of-bounds which implies it's on the last line, or there's no newlines
        // at all and there's only one line.
        let size = self.newline_positions.len();
        if size == 0 {
            return 1;
        } else if idx >= size {
            return size + 1;
        }

        let newline_pos = self.newline_positions[idx];

        // Add 1 to go from 0-indexed to 1-indexed, then might have to add another to account for
        // how the line is _after_ the newline.
        if pos <= newline_pos { idx + 1 } else { idx + 2 }
    }
}

pub fn file_source_type(path: &Path) -> Option<PySourceType> {
    match path.extension().and_then(|e| e.to_str()) {
        Some("py") => Some(PySourceType::Python),
        Some("pyi") => Some(PySourceType::Stub),
        _ => None,
    }
}

fn is_thrift_generated(source: &str) -> bool {
    // Only inspect the file header; the marker is ASCII, so scan the raw bytes to
    // avoid a UTF-8 boundary miss that would fall back to scanning the whole file.
    const MARKER: &[u8] = b"# Autogenerated by Thrift";
    let prefix = &source.as_bytes()[..source.len().min(256)];
    prefix.windows(MARKER.len()).any(|w| w == MARKER)
}

/// Parse `source` into a `ParsedModule` via ruff's error recovery: never fails,
/// yielding a best-effort AST even for source with syntax errors, capturing the
/// first reported error in `first_syntax_error`. The real-file read boundary
/// surfaces that error (treating a broken file as missing); test snippets and
/// embedded stubs, which are often partial or synthetic, ignore it.
pub fn parse_file(
    source: &str,
    typ: PySourceType,
    name: ModuleName,
    is_init: bool,
    version: PythonVersion,
) -> ParsedModule {
    let options = ParseOptions::from(typ).with_target_version(to_ruff_version(&version));
    let parsed = ruff_python_parser::parse_unchecked(source, options);
    let first_syntax_error = parsed.errors().first().map(|err| err.to_string());
    build_parsed_module(
        parsed.into_syntax(),
        source,
        typ,
        name,
        is_init,
        first_syntax_error,
    )
}

/// Assemble a `ParsedModule` from a parsed module AST: record line offsets and
/// flag Thrift-generated codegen.
fn build_parsed_module(
    parsed: Mod,
    source: &str,
    typ: PySourceType,
    name: ModuleName,
    is_init: bool,
    first_syntax_error: Option<String>,
) -> ParsedModule {
    let Mod::Module(ast) = parsed else {
        unreachable!("PySourceType::Python and ::Stub always produce Mod::Module")
    };
    let is_thrift = typ == PySourceType::Python
        && (name.as_str().ends_with(".ttypes") || name.as_str().ends_with(".thrift_types"))
        && is_thrift_generated(source);
    ParsedModule {
        name,
        ast,
        source_type: typ,
        is_init,
        is_thrift_generated: is_thrift,
        first_syntax_error,
        newline_positions: compute_newline_positions(source),
    }
}

pub fn parse_source(source: &str, module_name: ModuleName, is_init: bool) -> ParsedModule {
    parse_file(
        source,
        PySourceType::Python,
        module_name,
        is_init,
        default_python_version(),
    )
}

pub fn parse_source_with_version(
    source: &str,
    module_name: ModuleName,
    is_init: bool,
    version: PythonVersion,
) -> ParsedModule {
    parse_file(source, PySourceType::Python, module_name, is_init, version)
}

pub fn parse_pyi(source: &str, module_name: ModuleName, is_init: bool) -> ParsedModule {
    parse_file(
        source,
        PySourceType::Stub,
        module_name,
        is_init,
        default_python_version(),
    )
}

pub fn parse_pyi_with_version(
    source: &str,
    module_name: ModuleName,
    is_init: bool,
    version: PythonVersion,
) -> ParsedModule {
    parse_file(source, PySourceType::Stub, module_name, is_init, version)
}

pub fn read_and_parse_source(
    path: &PathBuf,
    module_name: ModuleName,
    is_init: bool,
) -> Result<ParsedModule> {
    read_and_parse_source_with_version(path, module_name, is_init, default_python_version())
}

pub fn read_and_parse_source_with_version(
    path: &PathBuf,
    module_name: ModuleName,
    is_init: bool,
    version: PythonVersion,
) -> Result<ParsedModule> {
    let bytes = std::fs::read(path)?;
    match String::from_utf8_lossy(&bytes) {
        // Valid UTF-8: a real syntax error surfaces as `Err` (the module is then
        // treated as missing downstream) rather than analyzed partially.
        std::borrow::Cow::Borrowed(source) => {
            let module = parse_file(source, PySourceType::Python, module_name, is_init, version);
            if let Some(err) = &module.first_syntax_error {
                anyhow::bail!("failed to parse {}: {}", module_name.as_str(), err);
            }
            Ok(module)
        }
        // Non-UTF-8, lossily decoded: keep the best-effort AST so replacement
        // chars don't turn otherwise-valid encoded Python into a hard failure.
        std::borrow::Cow::Owned(source) => Ok(parse_file(
            &source,
            PySourceType::Python,
            module_name,
            is_init,
            version,
        )),
    }
}

/// Sorted byte offsets of every `\n` in `source`. Scans raw bytes, not `chars()`, so offsets match
/// ruff's byte-based AST positions — `\n` (0x0A) never occurs inside a multi-byte UTF-8 sequence.
fn compute_newline_positions(source: &str) -> Vec<u32> {
    source
        .as_bytes()
        .iter()
        .enumerate()
        .filter_map(|(index, &byte)| (byte == b'\n').then_some(index as u32))
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    fn make_parsed(source: &str) -> ParsedModule {
        parse_source(source, ModuleName::from_str("test"), false)
    }

    #[test]
    fn thrift_generated_detection() {
        let header = concat!("#\n# Autogenerated by Thrift\n#\n#  @", "generated\n#\n");
        let is_gen = |name: &str, src: &str| {
            parse_source(src, ModuleName::from_str(name), false).is_thrift_generated
        };
        // thrift-py-deprecated `.ttypes` and thrift-python `.thrift_types` with marker.
        assert!(is_gen("pkg.foo.ttypes", header));
        assert!(is_gen("pkg.foo.thrift_types", header));
        // Marker present but a non-generated module name.
        assert!(!is_gen("pkg.foo.bar", header));
        // Generated suffix but no autogenerated marker.
        assert!(!is_gen("pkg.foo.thrift_types", "x = 1\n"));
    }

    #[test]
    fn parse_file_flags_syntax_errors() {
        let broken = parse_file(
            "def f(:\n",
            PySourceType::Python,
            ModuleName::from_str("broken"),
            false,
            default_python_version(),
        );
        assert!(
            broken.first_syntax_error.is_some(),
            "invalid source should capture a syntax error"
        );

        let ok = parse_file(
            "def f():\n    pass\n",
            PySourceType::Python,
            ModuleName::from_str("ok"),
            false,
            default_python_version(),
        );
        assert!(
            ok.first_syntax_error.is_none(),
            "valid source has no syntax error"
        );
    }

    #[test]
    fn empty_file() {
        let m = make_parsed("");
        assert_eq!(m.byte_to_line_number(0), 1, "empty file returns line 1");
    }

    #[test]
    fn single_line_no_newline() {
        let m = make_parsed("hello");
        assert_eq!(m.byte_to_line_number(0), 1, "position 0 is on line 1");
        assert_eq!(m.byte_to_line_number(3), 1, "position 3 is on line 1");
        assert_eq!(m.byte_to_line_number(4), 1, "position 4 is on line 1");
    }

    #[test]
    fn position_at_newline_boundary() {
        // "ab\ncd\n" -> newlines at positions 2 and 5
        let m = make_parsed("ab\ncd\n");
        assert_eq!(m.byte_to_line_number(2), 1, "at first newline");
        assert_eq!(m.byte_to_line_number(5), 2, "at second newline");
    }

    #[test]
    fn position_past_eof() {
        // "a\nb\n" -> newlines at positions 1 and 3
        let m = make_parsed("a\nb\n");
        assert_eq!(m.newline_positions.len(), 2);
        // Past EOF returns one line past the last newline
        assert_eq!(
            m.byte_to_line_number(100),
            3,
            "past EOF returns last line number"
        );
    }

    #[test]
    fn non_ascii_newlines_are_byte_offsets() {
        // "é" is 2 bytes (0xC3 0xA9) in UTF-8, so byte layout of "é\nx" is:
        //   é = bytes 0..2, '\n' = byte 2, 'x' = byte 3
        // Newline positions must be byte offsets (matching ruff), not char indices.
        let m = make_parsed("é\nx");
        assert_eq!(
            m.newline_positions,
            vec![2],
            "newline stored as byte offset (2), not char index (1)"
        );
        assert_eq!(m.byte_to_line_number(0), 1, "byte 0 (inside é) is line 1");
        assert_eq!(
            m.byte_to_line_number(3),
            2,
            "byte 3 (x, after newline) is line 2"
        );
    }

    #[test]
    fn multi_line_various_positions() {
        // "line1\nline2\nline3"
        // newlines at positions 5 and 11
        let m = make_parsed("line1\nline2\nline3");
        assert_eq!(m.byte_to_line_number(0), 1, "start of line 1");
        assert_eq!(m.byte_to_line_number(4), 1, "end of line 1 content");
        assert_eq!(m.byte_to_line_number(5), 1, "at first newline");
        assert_eq!(m.byte_to_line_number(6), 2, "start of line 2");
        assert_eq!(m.byte_to_line_number(11), 2, "at second newline");
        // Positions past the last newline are on the last line
        assert_eq!(m.byte_to_line_number(12), 3, "start of line 3");
        assert_eq!(m.byte_to_line_number(16), 3, "end of file");
    }
}
