name: lifeguard
on:
  push:
    paths:
      - '**/*'
      - '!.*'
      - '.github/workflows/lifeguard.yml'
  pull_request:
  schedule:
    - cron: '0 12 * * 1' # 12pm Monday
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
      with:
        submodules: recursive
    - run: rustup show
    - run: rustup component add clippy rustfmt
    - uses: Swatinem/rust-cache@v2
      with:
        prefix-key: lifeguard
    - run: cargo fmt -- --check
    - run: cargo clippy --locked
    - run: cargo test --locked
    - run: cargo build --bin analyzer --release --locked
