name: lifeguard
on:
  push:
    paths:
      - '**/*'
      - '!.*'
      - '.github/workflows/lifeguard.yml'
  pull_request:
  schedule:
    - cron: '0 12 * * 1' # 12pm Monday

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        submodules: recursive
        persist-credentials: false
    - uses: dtolnay/rust-toolchain@29eef336d9b2848a0b548edc03f92a220660cdb8 # stable
      with:
        toolchain: nightly-2026-05-22
        components: clippy, rustfmt
    - uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
      with:
        prefix-key: lifeguard
    - run: cargo fmt -- --check
    - run: cargo clippy --release
    - run: cargo test --release
    - run: cargo build --bin lifeguard --release
